name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:latest ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve -var="app_image=${{ secrets.DOCKER_USERNAME }}/python-app:latest"

      - name: ECS Service Restart (optional)
        run: |
          aws ecs update-service \
            --cluster python-redis-cluster \
            --service python-redis-service \
            --force-new-deployment \
            --region $AWS_REGION
